/**
 * String templates for files `pyanchor init` writes + the
 * "next steps" instructions it prints when it can't safely
 * auto-edit the host's source (JSX/TSX patching is risky enough
 * that we leave it to the user — a printed snippet they can copy
 * into layout.tsx beats a regex that might mangle their code).
 */

import type { AgentBin, Framework, RouterKind } from "./detect";

export interface EnvTemplateInput {
  token: string;
  agent: AgentBin;
  framework: Framework;
  appDir: string;
  workspaceDir: string;
  restartScript: string;
  healthcheckUrl: string;
  port: number;
  requireGate: boolean;
  allowedOrigins: string[];
  outputMode: "apply" | "pr" | "dryrun";
}

export function renderEnv(input: EnvTemplateInput): string {
  const lines = [
    `# Generated by \`pyanchor init\` on ${new Date().toISOString()}.`,
    `# Edit freely — pyanchor reads these as plain env vars.`,
    `# Full reference: https://github.com/pyanchor/pyanchor/blob/main/.env.example`,
    ``,
    `PYANCHOR_TOKEN=${input.token}`,
    `PYANCHOR_AGENT=${input.agent}`,
    `PYANCHOR_FRAMEWORK=${input.framework === "unknown" ? "nextjs" : input.framework}`,
    `PYANCHOR_APP_DIR=${input.appDir}`,
    `PYANCHOR_WORKSPACE_DIR=${input.workspaceDir}`,
    `PYANCHOR_RESTART_SCRIPT=${input.restartScript}`,
    `PYANCHOR_HEALTHCHECK_URL=${input.healthcheckUrl}`,
    `PYANCHOR_PORT=${input.port}`,
    input.allowedOrigins.length > 0
      ? `PYANCHOR_ALLOWED_ORIGINS=${input.allowedOrigins.join(",")}`
      : `# PYANCHOR_ALLOWED_ORIGINS=https://app.example.com  # set in production`,
    input.outputMode !== "apply" ? `PYANCHOR_OUTPUT_MODE=${input.outputMode}` : `# PYANCHOR_OUTPUT_MODE=apply  # apply | pr | dryrun`,
    input.requireGate ? `PYANCHOR_REQUIRE_GATE_COOKIE=true` : `# PYANCHOR_REQUIRE_GATE_COOKIE=true  # production gate`,
    `# Enable for an append-only audit trail of every edit.`,
    `# PYANCHOR_AUDIT_LOG=true`,
    ``
  ];
  return lines.filter((l) => l !== null).join("\n");
}

export interface RestartTemplateInput {
  /** Which preset the user picked. */
  approach: "noop" | "pm2" | "systemctl" | "docker" | "custom";
  /** Process / unit / container name (depends on approach). */
  name: string;
}

export function renderRestartScript(input: RestartTemplateInput): string {
  const header = [
    `#!/usr/bin/env bash`,
    `# Generated by \`pyanchor init\` on ${new Date().toISOString()}.`,
    `# Pyanchor invokes this AFTER a successful build to restart your`,
    `# frontend so the new code goes live. Exit 0 = success.`,
    `set -euo pipefail`,
    ``
  ].join("\n");

  switch (input.approach) {
    case "noop":
      return [
        header,
        `# next/vite/astro dev servers hot-reload on rsync, so no explicit`,
        `# restart is needed in dev. In production, edit this script to`,
        `# point at your real process manager (pm2, systemctl, docker).`,
        `exit 0`,
        ``
      ].join("\n");
    case "pm2":
      return [
        header,
        `exec /usr/bin/pm2 reload ${input.name}`,
        ``
      ].join("\n");
    case "systemctl":
      return [
        header,
        `exec /usr/bin/sudo /usr/bin/systemctl restart ${input.name}`,
        ``
      ].join("\n");
    case "docker":
      return [
        header,
        `exec /usr/bin/docker restart ${input.name}`,
        ``
      ].join("\n");
    case "custom":
    default:
      return [
        header,
        `# TODO: replace this with your real restart command.`,
        `echo "no-op restart — edit ${input.name} or scripts/restart.sh"`,
        `exit 0`,
        ``
      ].join("\n");
  }
}

/**
 * The bootstrap script tag the user has to paste into their global
 * layout. We print this to stdout instead of patching JSX/TSX
 * automatically — string-based JSX manipulation is fragile and the
 * cost of getting it wrong (broken layout) is much higher than the
 * cost of asking the user to copy 4 lines.
 */
export function renderBootstrapSnippet(framework: Framework, routerKind: RouterKind): string {
  const tag = `<script src="/_pyanchor/bootstrap.js" defer data-pyanchor-token={process.env.NEXT_PUBLIC_PYANCHOR_TOKEN}></script>`;
  const tagPlain = `<script src="/_pyanchor/bootstrap.js" defer data-pyanchor-token="REPLACE_WITH_PYANCHOR_TOKEN"></script>`;

  if (framework === "nextjs" && routerKind === "app") {
    return [
      `Add to app/layout.tsx (or src/app/layout.tsx) inside <head>:`,
      ``,
      `  ${tag}`,
      ``,
      `Then expose the token to the client by adding to your .env.local:`,
      `  NEXT_PUBLIC_PYANCHOR_TOKEN=<same value as PYANCHOR_TOKEN above>`
    ].join("\n");
  }

  if (framework === "nextjs" && routerKind === "pages") {
    return [
      `Add to pages/_document.tsx inside <Head> (or wrap in <Script> from next/script):`,
      ``,
      `  ${tag}`,
      ``,
      `Then expose the token to the client by adding to your .env.local:`,
      `  NEXT_PUBLIC_PYANCHOR_TOKEN=<same value as PYANCHOR_TOKEN above>`
    ].join("\n");
  }

  if (framework === "vite") {
    return [
      `Add to index.html inside <head>:`,
      ``,
      `  ${tagPlain}`,
      ``,
      `Then in vite.config.ts add a dev proxy:`,
      ``,
      `  server: { proxy: { "/_pyanchor": { target: "http://127.0.0.1:3010", changeOrigin: false } } }`
    ].join("\n");
  }

  if (framework === "astro") {
    return [
      `Add to src/layouts/Base.astro (or whatever wraps every page) inside <head>:`,
      ``,
      `  ${tagPlain}`,
      ``,
      `Astro uses Vite under the hood — add to astro.config.mjs:`,
      ``,
      `  vite: { server: { proxy: { "/_pyanchor": { target: "http://127.0.0.1:3010", changeOrigin: false } } } }`
    ].join("\n");
  }

  return [
    `Add to your global HTML template (whatever renders <head> for every page):`,
    ``,
    `  ${tagPlain}`,
    ``,
    `Then add a /_pyanchor/* dev proxy to whatever serves your app on dev so the`,
    `bootstrap script can reach the sidecar at 127.0.0.1:3010.`
  ].join("\n");
}

/**
 * For Next.js, also prompt the user to add a rewrite to next.config.mjs.
 */
export function renderNextConfigSnippet(): string {
  return [
    `Add a /_pyanchor/* rewrite to next.config.mjs (or next.config.js):`,
    ``,
    `  /** @type {import('next').NextConfig} */`,
    `  const nextConfig = {`,
    `    async rewrites() {`,
    `      return [{ source: "/_pyanchor/:path*", destination: "http://127.0.0.1:3010/_pyanchor/:path*" }];`,
    `    }`,
    `  };`,
    `  export default nextConfig;`
  ].join("\n");
}
