/**
 * String templates for files `pyanchor init` writes + the
 * "next steps" instructions it prints when it can't safely
 * auto-edit the host's source (JSX/TSX patching is risky enough
 * that we leave it to the user — a printed snippet they can copy
 * into layout.tsx beats a regex that might mangle their code).
 */

import type { AgentBin, Framework, RouterKind } from "./detect";

/**
 * v0.28.1 — round 18 P2 fix. Quote a value for shell consumption
 * (POSIX `sh` / `bash` / `zsh`). Plain ASCII identifiers, paths
 * without special chars, version strings etc. round-trip unchanged
 * so the common case stays readable. Anything else gets single-quoted
 * with embedded single quotes escaped via `'\''`.
 *
 * The `.env.local` we write is consumed by both the sidecar process
 * (`process.env`-style readers don't care about quoting) AND by users
 * who `source .env.local` from a shell, where quoting matters. Pre-
 * v0.28.1 paths containing spaces (common on macOS) broke the latter
 * with "Too many arguments". Path values are always quoted now.
 */
export function shellQuote(value: string): string {
  if (value === "") return "''";
  if (/^[A-Za-z0-9_./:@%+=,-]+$/.test(value)) return value;
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export interface EnvTemplateInput {
  token: string;
  agent: AgentBin;
  framework: Framework;
  appDir: string;
  workspaceDir: string;
  restartScript: string;
  healthcheckUrl: string;
  port: number;
  requireGate: boolean;
  allowedOrigins: string[];
  outputMode: "apply" | "pr" | "dryrun";
  /**
   * v0.29.0 (round 18 recommendation 6): when true, also emit
   * `NEXT_PUBLIC_PYANCHOR_TOKEN=<token>` so the host app's bootstrap
   * `<script data-pyanchor-token={process.env.NEXT_PUBLIC_PYANCHOR_TOKEN}>`
   * resolves without an extra manual paste step. Only meaningful for
   * frameworks that read NEXT_PUBLIC_* on the client (Next.js).
   */
  nextPublicToken?: boolean;
}

export function renderEnv(input: EnvTemplateInput): string {
  const lines = [
    `# Generated by \`pyanchor init\` on ${new Date().toISOString()}.`,
    `# Edit freely — pyanchor reads these as plain env vars.`,
    `# Full reference: https://github.com/pyanchor/pyanchor/blob/main/.env.example`,
    ``,
    `PYANCHOR_TOKEN=${input.token}`,
    `PYANCHOR_AGENT=${input.agent}`,
    `PYANCHOR_FRAMEWORK=${input.framework === "unknown" ? "nextjs" : input.framework}`,
    `PYANCHOR_APP_DIR=${shellQuote(input.appDir)}`,
    `PYANCHOR_WORKSPACE_DIR=${shellQuote(input.workspaceDir)}`,
    `PYANCHOR_RESTART_SCRIPT=${shellQuote(input.restartScript)}`,
    `PYANCHOR_HEALTHCHECK_URL=${shellQuote(input.healthcheckUrl)}`,
    `PYANCHOR_PORT=${input.port}`,
    input.allowedOrigins.length > 0
      ? `PYANCHOR_ALLOWED_ORIGINS=${shellQuote(input.allowedOrigins.join(","))}`
      : `# PYANCHOR_ALLOWED_ORIGINS=https://app.example.com  # set in production`,
    input.outputMode !== "apply" ? `PYANCHOR_OUTPUT_MODE=${input.outputMode}` : `# PYANCHOR_OUTPUT_MODE=apply  # apply | pr | dryrun`,
    input.requireGate ? `PYANCHOR_REQUIRE_GATE_COOKIE=true` : `# PYANCHOR_REQUIRE_GATE_COOKIE=true  # production gate`,
    `# Enable for an append-only audit trail of every edit.`,
    `# PYANCHOR_AUDIT_LOG=true`,
    input.nextPublicToken
      ? [
          ``,
          `# v0.29.0 — exposed to the Next.js client so the bootstrap`,
          `# script tag's data-pyanchor-token attribute resolves at`,
          `# build time. Same value as PYANCHOR_TOKEN above.`,
          `NEXT_PUBLIC_PYANCHOR_TOKEN=${input.token}`
        ].join("\n")
      : null,
    ``
  ];
  return lines.filter((l) => l !== null).join("\n");
}

export interface RestartTemplateInput {
  /** Which preset the user picked. */
  approach: "noop" | "pm2" | "systemctl" | "docker" | "custom";
  /** Process / unit / container name (depends on approach). */
  name: string;
}

export function renderRestartScript(input: RestartTemplateInput): string {
  const header = [
    `#!/usr/bin/env bash`,
    `# Generated by \`pyanchor init\` on ${new Date().toISOString()}.`,
    `# Pyanchor invokes this AFTER a successful build to restart your`,
    `# frontend so the new code goes live. Exit 0 = success.`,
    `set -euo pipefail`,
    ``
  ].join("\n");

  switch (input.approach) {
    case "noop":
      return [
        header,
        `# next/vite/astro dev servers hot-reload on rsync, so no explicit`,
        `# restart is needed in dev. In production, edit this script to`,
        `# point at your real process manager (pm2, systemctl, docker).`,
        `exit 0`,
        ``
      ].join("\n");
    // v0.33.0 — shellQuote(input.name) so a project dir / prompt
    // input like `my-app; touch /tmp/pwned` can't smuggle commands
    // into the generated restart.sh. The systemctl preset is
    // particularly sensitive because it runs under sudo. Caught by
    // codex static audit.
    case "pm2":
      return [
        header,
        `exec /usr/bin/pm2 reload ${shellQuote(input.name)}`,
        ``
      ].join("\n");
    case "systemctl":
      return [
        header,
        `exec /usr/bin/sudo /usr/bin/systemctl restart ${shellQuote(input.name)}`,
        ``
      ].join("\n");
    case "docker":
      return [
        header,
        `exec /usr/bin/docker restart ${shellQuote(input.name)}`,
        ``
      ].join("\n");
    case "custom":
    default:
      return [
        header,
        `# TODO: replace this with your real restart command.`,
        `echo "no-op restart — edit ${input.name} or scripts/restart.sh"`,
        `exit 0`,
        ``
      ].join("\n");
  }
}

/**
 * The bootstrap script tag the user has to paste into their global
 * layout. We print this to stdout instead of patching JSX/TSX
 * automatically — string-based JSX manipulation is fragile and the
 * cost of getting it wrong (broken layout) is much higher than the
 * cost of asking the user to copy 4 lines.
 */
export function renderBootstrapSnippet(
  framework: Framework,
  routerKind: RouterKind,
  // v0.32.2 — caller passes the actual sidecar port + plain-text
  // token so the snippet is paste-ready. Pre-v0.32.2 we hardcoded
  // port 3010 even when init asked the user for a different port,
  // and the token placeholder said "REPLACE_WITH_PYANCHOR_TOKEN"
  // with no hint of where to find the real value.
  port: number = 3010,
  tokenForPaste?: string
): string {
  const tokenAttr = tokenForPaste ?? "REPLACE_WITH_PYANCHOR_TOKEN";
  const tokenNote = tokenForPaste
    ? `(token shown above is the freshly generated one written to your .env)`
    : `(replace REPLACE_WITH_PYANCHOR_TOKEN with the PYANCHOR_TOKEN value from your .env)`;
  const tag = `<script src="/_pyanchor/bootstrap.js" defer data-pyanchor-token={process.env.NEXT_PUBLIC_PYANCHOR_TOKEN}></script>`;
  const tagPlain = `<script src="/_pyanchor/bootstrap.js" defer data-pyanchor-token="${tokenAttr}"></script>`;
  const proxyTarget = `http://127.0.0.1:${port}`;

  if (framework === "nextjs" && routerKind === "app") {
    return [
      `Add to app/layout.tsx (or src/app/layout.tsx) inside <head>:`,
      ``,
      `  ${tag}`,
      ``,
      `(NEXT_PUBLIC_PYANCHOR_TOKEN is already in your .env.local — Next.js inlines it at build time.)`
    ].join("\n");
  }

  if (framework === "nextjs" && routerKind === "pages") {
    return [
      `Add to pages/_document.tsx inside <Head> (or wrap in <Script> from next/script):`,
      ``,
      `  ${tag}`,
      ``,
      `(NEXT_PUBLIC_PYANCHOR_TOKEN is already in your .env.local — Next.js inlines it at build time.)`
    ].join("\n");
  }

  if (framework === "vite") {
    return [
      `Add to index.html inside <head>:`,
      ``,
      `  ${tagPlain}`,
      `  ${tokenNote}`,
      ``,
      `Then in vite.config.ts add a dev proxy:`,
      ``,
      `  server: { proxy: { "/_pyanchor": { target: "${proxyTarget}", changeOrigin: false } } }`,
      ``,
      PROD_HOSTS_HINT
    ].join("\n");
  }

  if (framework === "astro") {
    return [
      `Add to src/layouts/Base.astro (or whatever wraps every page) inside <head>:`,
      ``,
      `  ${tagPlain}`,
      `  ${tokenNote}`,
      ``,
      `Astro uses Vite under the hood — add to astro.config.mjs:`,
      ``,
      `  vite: { server: { proxy: { "/_pyanchor": { target: "${proxyTarget}", changeOrigin: false } } } }`,
      ``,
      PROD_HOSTS_HINT
    ].join("\n");
  }

  return [
    `Add to your global HTML template (whatever renders <head> for every page):`,
    ``,
    `  ${tagPlain}`,
    `  ${tokenNote}`,
    ``,
    `Then add a /_pyanchor/* dev proxy to whatever serves your app on dev so the`,
    `bootstrap script can reach the sidecar at ${proxyTarget}.`,
    ``,
    PROD_HOSTS_HINT
  ].join("\n");
}

// v0.32.4 — surface the prod-deployment caveat that bit a reviewer
// during the pyanchor-demo onboarding sim: bootstrap.ts trusts
// localhost / 127.0.0.1 by default, so a `data-pyanchor-token` snippet
// pasted into a real-domain deployment silently no-ops with a
// "[pyanchor] overlay disabled on untrusted host" console.warn. Easy
// to miss because the sidecar still serves bootstrap.js + the gate
// cookie still works — but the overlay never mounts. Inline the
// fix here so users see it the moment init prints the snippet,
// not after the first browser visit fails.
const PROD_HOSTS_HINT =
  `Production hostname tip: the bootstrap script trusts localhost / 127.0.0.1 by\n` +
  `default. To run on a real domain, add data-pyanchor-trusted-hosts (CSV)\n` +
  `and (optionally) data-pyanchor-require-gate-cookie to the same <script> tag:\n` +
  `\n` +
  `  data-pyanchor-trusted-hosts="your-domain.com,localhost,127.0.0.1"\n` +
  `  data-pyanchor-require-gate-cookie="pyanchor_dev"\n` +
  `\n` +
  `See docs/ACCESS-CONTROL.md for the full 9-layer model + gate-cookie setup.`;

/**
 * For Next.js, also prompt the user to add a rewrite to next.config.mjs.
 *
 * v0.32.2 — port is now passed in so the snippet matches the user's
 * actual sidecar port. Pre-v0.32.2 we hardcoded 3010.
 */
export function renderNextConfigSnippet(port: number = 3010): string {
  const dest = `http://127.0.0.1:${port}/_pyanchor/:path*`;
  return [
    `Add a /_pyanchor/* rewrite to next.config.mjs (or next.config.js):`,
    ``,
    `  /** @type {import('next').NextConfig} */`,
    `  const nextConfig = {`,
    `    async rewrites() {`,
    `      return [{ source: "/_pyanchor/:path*", destination: "${dest}" }];`,
    `    }`,
    `  };`,
    `  export default nextConfig;`
  ].join("\n");
}
